version: '3'

services:
  nginx:
    image: nginx:1.15.8
    container_name: 'nginx-container-prod'
    working_dir: /app
    ports:
      - '80:80'
    volumes:
      - ./backend_src:/app/backend
      - ./config/keys:/app/backend/config/jwt
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/backend/public/uploads
      - ./media:/app/backend/public/media
      - ./frontend_src/dist/red-button-frontend:/app/frontend
    links:
      - php-fpm-service

  php-fpm-service:
    build:
      context: .
      dockerfile: php-fpm.docker
    container_name: 'php-fpm-container-prod'
    working_dir: /app/backend
    ports:
      - '9000:9000'
    volumes:
      - ./backend_src:/app/backend
      - ./config/keys:/app/backend/config/jwt
      - ./uploads:/app/backend/public/uploads
      - ./media:/app/backend/public/media
    links:
      - postgres_db
    env_file:
      - ./config/.env.prod

  postgres_db:
    image: mdillon/postgis:10
    container_name: 'postgres-db-container-prod'
    restart: always
    ports:
      - '7778:5432'
    volumes:
      - red_button_database_volume_prod:/var/lib/postgresql/data
    env_file:
      - ./config/.env.prod

volumes:
  red_button_database_volume_prod:
