version: '3'

services:
  nginx:
    image: nginx:1.15.8
    container_name: 'nginx-container-prod'
    working_dir: /app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./backend_src:/app/backend
      - ./config/keys:/app/backend/config/jwt
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/letsencrypt
      - ./uploads:/app/backend/public/uploads
      - ./media:/app/backend/public/media
      - ./frontend_src/dist/red-button-frontend:/app/frontend
    links:
      - php-fpm-service

  php-fpm-service:
    build:
      context: .
      dockerfile: php-fpm.docker
    container_name: 'php-fpm-container-prod'
    working_dir: /app/backend
    ports:
      - '9000:9000'
    volumes:
      - ./backend_src:/app/backend
      - ./config/keys:/app/backend/config/jwt
      - ./uploads:/app/backend/public/uploads
      - ./media:/app/backend/public/media
    links:
      - postgres_db
      - mailer-service
    env_file:
      - ./config/.env.prod

  postgres_db:
    image: mdillon/postgis:10
    container_name: 'postgres-db-container-prod'
    restart: always
    ports:
      - '7778:5432'
    volumes:
      - red_button_database_volume_prod:/var/lib/postgresql/data
    env_file:
      - ./config/.env.prod

  mailer-service:
    image: catatnight/postfix
    hostname: 'mail'
    domainname: 'rbutton.ru'
    container_name: 'mailer-service-prod'
    ports:
      - "25:25"
    volumes:
      - ./config/mailer/opendkim:/etc/opendkim
      - /etc/letsencrypt/live/rbutton.ru/fullchain.pem:/etc/postfix/certs/public.crt
      - /etc/letsencrypt/live/rbutton.ru/privkey.pem:/etc/postfix/certs/private.key
    env_file:
      - ./config/.env.mailer
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  red_button_database_volume_prod: